// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0CVpWCU4iz8Xvm2owUxbZlVKHyGg4Gsw',
    appId: '1:855187123216:web:5a6a09ad27b2f826bfae95',
    messagingSenderId: '855187123216',
    projectId: 'lodge-app-da2a2',
    authDomain: 'lodge-app-da2a2.firebaseapp.com',
    storageBucket: 'lodge-app-da2a2.appspot.com',
    measurementId: 'G-YC8V2RTXXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP8phrFtjS7BB251NYGvsUlgZYvf2EBz4',
    appId: '1:855187123216:android:1955d26cb4a3e37fbfae95',
    messagingSenderId: '855187123216',
    projectId: 'lodge-app-da2a2',
    storageBucket: 'lodge-app-da2a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4HUFSZTGKGKa8z19M2fz47i39wvppGfk',
    appId: '1:855187123216:ios:f3f5f02c4a70eec0bfae95',
    messagingSenderId: '855187123216',
    projectId: 'lodge-app-da2a2',
    storageBucket: 'lodge-app-da2a2.appspot.com',
    iosBundleId: 'com.example.lodgeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4HUFSZTGKGKa8z19M2fz47i39wvppGfk',
    appId: '1:855187123216:ios:aba0622eb77ea14cbfae95',
    messagingSenderId: '855187123216',
    projectId: 'lodge-app-da2a2',
    storageBucket: 'lodge-app-da2a2.appspot.com',
    iosBundleId: 'com.example.lodgeManagementApp.RunnerTests',
  );
}
